server:
  address: localhost
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '0000'
    url: jdbc:mysql://localhost:3306/englishstudyapp?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: englishstudy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
  #h2:
    #console:
      #enabled: true